const mongoose = require('mongoose');
require('dotenv').config();
const connectDB = require('./config/database');
const Product = require('./models/Product');
const Coupon = require('./models/Coupon');

const products = [
  // Electronics - Smartphones & Accessories
  { name: 'iPhone 15 Pro Max', description: 'Latest flagship smartphone with A17 Pro chip, titanium design, and ProRAW photography', price: 1199.99, originalPrice: 1299.99, category: 'Electronics', subcategory: 'Smartphones', brand: 'Apple', image: 'https://via.placeholder.com/300x300?text=iPhone+15+Pro', stock: 45, rating: 4.8, reviews: 1250, tags: ['smartphone', 'apple', 'premium'], purchaseOptions: ['standard', 'express', 'premium'], popularity: 95 },
  { name: 'Samsung Galaxy S24 Ultra', description: 'Premium Android phone with S Pen, 200MP camera, and Snapdragon 8 Gen 3', price: 1099.99, originalPrice: 1199.99, category: 'Electronics', subcategory: 'Smartphones', brand: 'Samsung', image: 'https://via.placeholder.com/300x300?text=Galaxy+S24', stock: 38, rating: 4.7, reviews: 980, tags: ['smartphone', 'android', 'samsung'], purchaseOptions: ['standard', 'express', 'warranty'], popularity: 92 },
  { name: 'Google Pixel 8 Pro', description: 'AI-powered camera phone with Tensor G3 chip and Magic Eraser', price: 899.99, originalPrice: 999.99, category: 'Electronics', subcategory: 'Smartphones', brand: 'Google', image: 'https://via.placeholder.com/300x300?text=Pixel+8', stock: 52, rating: 4.6, reviews: 756, tags: ['smartphone', 'android', 'google'], purchaseOptions: ['standard', 'express'], popularity: 88 },
  { name: 'OnePlus 12', description: 'Flagship killer with Snapdragon 8 Gen 3, 120Hz display, and fast charging', price: 699.99, originalPrice: 799.99, category: 'Electronics', subcategory: 'Smartphones', brand: 'OnePlus', image: 'https://via.placeholder.com/300x300?text=OnePlus+12', stock: 67, rating: 4.5, reviews: 432, tags: ['smartphone', 'android', 'oneplus'], purchaseOptions: ['standard', 'express'], popularity: 85 },
  { name: 'Wireless Charging Pad', description: '15W fast wireless charger compatible with all Qi-enabled devices', price: 29.99, originalPrice: 39.99, category: 'Electronics', subcategory: 'Accessories', brand: 'Anker', image: 'https://via.placeholder.com/300x300?text=Wireless+Charger', stock: 150, rating: 4.4, reviews: 1234, tags: ['wireless', 'charger', 'qi'], purchaseOptions: ['standard'], popularity: 78 },
  
  // Electronics - Laptops & Computers
  { name: 'MacBook Pro 16" M3 Max', description: 'Professional laptop with M3 Max chip, 16-inch Liquid Retina XDR display', price: 3499.99, originalPrice: 3799.99, category: 'Electronics', subcategory: 'Laptops', brand: 'Apple', image: 'https://via.placeholder.com/300x300?text=MacBook+Pro', stock: 25, rating: 4.9, reviews: 567, tags: ['laptop', 'apple', 'pro'], purchaseOptions: ['standard', 'express', 'premium', 'warranty'], popularity: 93 },
  { name: 'Dell XPS 15', description: 'Premium ultrabook with Intel i9, 4K OLED display, and NVIDIA RTX graphics', price: 1999.99, originalPrice: 2299.99, category: 'Electronics', subcategory: 'Laptops', brand: 'Dell', image: 'https://via.placeholder.com/300x300?text=XPS+15', stock: 32, rating: 4.7, reviews: 890, tags: ['laptop', 'dell', 'windows'], purchaseOptions: ['standard', 'express', 'warranty'], popularity: 90 },
  { name: 'HP Spectre x360', description: '2-in-1 convertible laptop with 13th Gen Intel processor and OLED touchscreen', price: 1499.99, originalPrice: 1699.99, category: 'Electronics', subcategory: 'Laptops', brand: 'HP', image: 'https://via.placeholder.com/300x300?text=Spectre', stock: 28, rating: 4.6, reviews: 654, tags: ['laptop', 'hp', '2-in-1'], purchaseOptions: ['standard', 'express'], popularity: 87 },
  { name: 'Lenovo ThinkPad X1 Carbon', description: 'Business laptop with Intel vPro, 14-inch display, and ThinkPad keyboard', price: 1799.99, originalPrice: 1999.99, category: 'Electronics', subcategory: 'Laptops', brand: 'Lenovo', image: 'https://via.placeholder.com/300x300?text=ThinkPad', stock: 41, rating: 4.8, reviews: 723, tags: ['laptop', 'lenovo', 'business'], purchaseOptions: ['standard', 'express', 'premium', 'warranty'], popularity: 89 },
  { name: 'Gaming Laptop RTX 4080', description: 'ASUS ROG Strix with RTX 4080, Intel i9, and 165Hz display', price: 2499.99, originalPrice: 2799.99, category: 'Electronics', subcategory: 'Laptops', brand: 'ASUS', image: 'https://via.placeholder.com/300x300?text=Gaming+Laptop', stock: 19, rating: 4.7, reviews: 445, tags: ['laptop', 'gaming', 'rtx'], purchaseOptions: ['standard', 'express', 'premium'], popularity: 86 },
  
  // Electronics - Audio
  { name: 'Sony WH-1000XM5 Headphones', description: 'Premium noise-cancelling wireless headphones with 30-hour battery', price: 349.99, originalPrice: 399.99, category: 'Electronics', subcategory: 'Audio', brand: 'Sony', image: 'https://via.placeholder.com/300x300?text=Sony+Headphones', stock: 58, rating: 4.8, reviews: 2156, tags: ['headphones', 'wireless', 'noise-cancelling'], purchaseOptions: ['standard', 'express'], popularity: 94 },
  { name: 'AirPods Pro 2', description: 'Apple wireless earbuds with active noise cancellation and spatial audio', price: 249.99, originalPrice: 279.99, category: 'Electronics', subcategory: 'Audio', brand: 'Apple', image: 'https://via.placeholder.com/300x300?text=AirPods+Pro', stock: 89, rating: 4.7, reviews: 3421, tags: ['earbuds', 'wireless', 'apple'], purchaseOptions: ['standard', 'express'], popularity: 96 },
  { name: 'Bose QuietComfort Earbuds', description: 'Industry-leading noise cancellation in true wireless earbuds', price: 279.99, originalPrice: 329.99, category: 'Electronics', subcategory: 'Audio', brand: 'Bose', image: 'https://via.placeholder.com/300x300?text=Bose+Earbuds', stock: 64, rating: 4.6, reviews: 1876, tags: ['earbuds', 'wireless', 'noise-cancelling'], purchaseOptions: ['standard', 'express'], popularity: 91 },
  { name: 'JBL Flip 6 Speaker', description: 'Portable Bluetooth speaker with IPX7 waterproof rating', price: 129.99, originalPrice: 149.99, category: 'Electronics', subcategory: 'Audio', brand: 'JBL', image: 'https://via.placeholder.com/300x300?text=JBL+Speaker', stock: 112, rating: 4.5, reviews: 2103, tags: ['speaker', 'bluetooth', 'portable'], purchaseOptions: ['standard'], popularity: 83 },
  { name: 'Audio-Technica ATH-M50x', description: 'Professional studio monitoring headphones with exceptional clarity', price: 149.99, originalPrice: 169.99, category: 'Electronics', subcategory: 'Audio', brand: 'Audio-Technica', image: 'https://via.placeholder.com/300x300?text=ATH-M50x', stock: 76, rating: 4.7, reviews: 1456, tags: ['headphones', 'studio', 'wired'], purchaseOptions: ['standard', 'express'], popularity: 82 },
  
  // Electronics - Wearables
  { name: 'Apple Watch Series 9', description: 'Smartwatch with S9 SiP chip, Always-On Retina display, and health tracking', price: 399.99, originalPrice: 429.99, category: 'Electronics', subcategory: 'Wearables', brand: 'Apple', image: 'https://via.placeholder.com/300x300?text=Apple+Watch', stock: 73, rating: 4.8, reviews: 2890, tags: ['smartwatch', 'apple', 'fitness'], purchaseOptions: ['standard', 'express'], popularity: 97 },
  { name: 'Samsung Galaxy Watch 6', description: 'Advanced health monitoring with ECG, BIA, and sleep tracking', price: 299.99, originalPrice: 349.99, category: 'Electronics', subcategory: 'Wearables', brand: 'Samsung', image: 'https://via.placeholder.com/300x300?text=Galaxy+Watch', stock: 61, rating: 4.6, reviews: 1678, tags: ['smartwatch', 'samsung', 'android'], purchaseOptions: ['standard', 'express'], popularity: 90 },
  { name: 'Fitbit Charge 6', description: 'Advanced fitness tracker with built-in GPS and Google services', price: 159.99, originalPrice: 179.99, category: 'Electronics', subcategory: 'Wearables', brand: 'Fitbit', image: 'https://via.placeholder.com/300x300?text=Fitbit', stock: 134, rating: 4.5, reviews: 3245, tags: ['fitness', 'tracker', 'health'], purchaseOptions: ['standard'], popularity: 85 },
  { name: 'Garmin Forerunner 955', description: 'Premium GPS running watch with advanced training metrics', price: 599.99, originalPrice: 649.99, category: 'Electronics', subcategory: 'Wearables', brand: 'Garmin', image: 'https://via.placeholder.com/300x300?text=Garmin', stock: 47, rating: 4.7, reviews: 987, tags: ['smartwatch', 'gps', 'running'], purchaseOptions: ['standard', 'express', 'warranty'], popularity: 88 },
  
  // Electronics - Gaming
  { name: 'PlayStation 5 Console', description: 'Next-gen gaming console with ray tracing and 3D audio', price: 499.99, originalPrice: 549.99, category: 'Electronics', subcategory: 'Gaming', brand: 'Sony', image: 'https://via.placeholder.com/300x300?text=PS5', stock: 34, rating: 4.9, reviews: 5678, tags: ['gaming', 'console', 'playstation'], purchaseOptions: ['standard', 'express', 'bundle'], popularity: 98 },
  { name: 'Xbox Series X', description: 'Most powerful Xbox console with 4K gaming at 120fps', price: 499.99, originalPrice: 549.99, category: 'Electronics', subcategory: 'Gaming', brand: 'Microsoft', image: 'https://via.placeholder.com/300x300?text=Xbox+X', stock: 29, rating: 4.8, reviews: 4321, tags: ['gaming', 'console', 'xbox'], purchaseOptions: ['standard', 'express', 'bundle'], popularity: 97 },
  { name: 'Nintendo Switch OLED', description: 'Handheld console with vibrant 7-inch OLED screen', price: 349.99, originalPrice: 379.99, category: 'Electronics', subcategory: 'Gaming', brand: 'Nintendo', image: 'https://via.placeholder.com/300x300?text=Switch', stock: 56, rating: 4.7, reviews: 6789, tags: ['gaming', 'console', 'portable'], purchaseOptions: ['standard', 'express'], popularity: 95 },
  { name: 'Gaming Mechanical Keyboard', description: 'RGB backlit keyboard with Cherry MX switches and wrist rest', price: 149.99, originalPrice: 179.99, category: 'Electronics', subcategory: 'Gaming', brand: 'Corsair', image: 'https://via.placeholder.com/300x300?text=Gaming+Keyboard', stock: 82, rating: 4.6, reviews: 2345, tags: ['keyboard', 'gaming', 'rgb'], purchaseOptions: ['standard', 'express'], popularity: 87 },
  { name: 'Gaming Mouse RGB', description: 'High-precision gaming mouse with 20,000 DPI sensor', price: 79.99, originalPrice: 99.99, category: 'Electronics', subcategory: 'Gaming', brand: 'Razer', image: 'https://via.placeholder.com/300x300?text=Gaming+Mouse', stock: 118, rating: 4.5, reviews: 3456, tags: ['mouse', 'gaming', 'rgb'], purchaseOptions: ['standard', 'express'], popularity: 86 },
  
  // Electronics - Cameras
  { name: 'Canon EOS R6 Mark II', description: 'Full-frame mirrorless camera with 24MP sensor and 4K video', price: 2499.99, originalPrice: 2699.99, category: 'Electronics', subcategory: 'Cameras', brand: 'Canon', image: 'https://via.placeholder.com/300x300?text=Canon+R6', stock: 23, rating: 4.8, reviews: 456, tags: ['camera', 'mirrorless', 'canon'], purchaseOptions: ['standard', 'express', 'premium', 'warranty'], popularity: 89 },
  { name: 'Sony A7 IV', description: 'Full-frame mirrorless with 33MP sensor and advanced autofocus', price: 2499.99, originalPrice: 2799.99, category: 'Electronics', subcategory: 'Cameras', brand: 'Sony', image: 'https://via.placeholder.com/300x300?text=Sony+A7', stock: 18, rating: 4.9, reviews: 789, tags: ['camera', 'mirrorless', 'sony'], purchaseOptions: ['standard', 'express', 'premium'], popularity: 91 },
  { name: 'GoPro Hero 12', description: 'Action camera with 5.3K video and HyperSmooth stabilization', price: 399.99, originalPrice: 449.99, category: 'Electronics', subcategory: 'Cameras', brand: 'GoPro', image: 'https://via.placeholder.com/300x300?text=GoPro', stock: 67, rating: 4.7, reviews: 1234, tags: ['camera', 'action', 'gopro'], purchaseOptions: ['standard', 'express'], popularity: 88 },
  
  // Electronics - Monitors & Displays
  { name: '4K Gaming Monitor 32"', description: 'LG UltraGear 32" 4K monitor with 144Hz refresh rate', price: 799.99, originalPrice: 899.99, category: 'Electronics', subcategory: 'Monitors', brand: 'LG', image: 'https://via.placeholder.com/300x300?text=4K+Monitor', stock: 42, rating: 4.7, reviews: 987, tags: ['monitor', '4k', 'gaming'], purchaseOptions: ['standard', 'express', 'warranty'], popularity: 87 },
  { name: 'Ultrawide Monitor 34"', description: 'Samsung Odyssey curved ultrawide with 1440p resolution', price: 599.99, originalPrice: 699.99, category: 'Electronics', subcategory: 'Monitors', brand: 'Samsung', image: 'https://via.placeholder.com/300x300?text=Ultrawide', stock: 51, rating: 4.6, reviews: 765, tags: ['monitor', 'ultrawide', 'curved'], purchaseOptions: ['standard', 'express'], popularity: 84 },
  { name: 'Portable Monitor 15.6"', description: 'USB-C powered portable monitor for laptops and phones', price: 199.99, originalPrice: 249.99, category: 'Electronics', subcategory: 'Monitors', brand: 'ASUS', image: 'https://via.placeholder.com/300x300?text=Portable+Monitor', stock: 88, rating: 4.4, reviews: 543, tags: ['monitor', 'portable', 'usb-c'], purchaseOptions: ['standard'], popularity: 79 },
  
  // Electronics - Smart Home
  { name: 'Amazon Echo Dot 5th Gen', description: 'Smart speaker with Alexa, improved sound quality', price: 49.99, originalPrice: 59.99, category: 'Electronics', subcategory: 'Smart Home', brand: 'Amazon', image: 'https://via.placeholder.com/300x300?text=Echo+Dot', stock: 156, rating: 4.5, reviews: 4567, tags: ['smart speaker', 'alexa', 'home'], purchaseOptions: ['standard', 'bulk'], popularity: 92 },
  { name: 'Google Nest Hub Max', description: '10-inch smart display with Google Assistant', price: 229.99, originalPrice: 279.99, category: 'Electronics', subcategory: 'Smart Home', brand: 'Google', image: 'https://via.placeholder.com/300x300?text=Nest+Hub', stock: 71, rating: 4.6, reviews: 2345, tags: ['smart display', 'google', 'assistant'], purchaseOptions: ['standard', 'express'], popularity: 86 },
  { name: 'Philips Hue Starter Kit', description: 'Smart lighting system with color bulbs and bridge', price: 199.99, originalPrice: 249.99, category: 'Electronics', subcategory: 'Smart Home', brand: 'Philips', image: 'https://via.placeholder.com/300x300?text=Hue+Kit', stock: 94, rating: 4.7, reviews: 3456, tags: ['smart lights', 'philips', 'hue'], purchaseOptions: ['standard', 'express'], popularity: 85 },
  { name: 'Ring Video Doorbell Pro', description: '1080p HD video doorbell with two-way talk', price: 249.99, originalPrice: 299.99, category: 'Electronics', subcategory: 'Smart Home', brand: 'Ring', image: 'https://via.placeholder.com/300x300?text=Ring+Doorbell', stock: 63, rating: 4.5, reviews: 4321, tags: ['doorbell', 'security', 'video'], purchaseOptions: ['standard', 'express'], popularity: 88 },
  { name: 'Nest Thermostat', description: 'Smart thermostat that learns your schedule', price: 249.99, originalPrice: 279.99, category: 'Electronics', subcategory: 'Smart Home', brand: 'Google', image: 'https://via.placeholder.com/300x300?text=Nest+Thermostat', stock: 87, rating: 4.6, reviews: 5678, tags: ['thermostat', 'smart', 'energy'], purchaseOptions: ['standard'], popularity: 83 },
  
  // Fashion - Clothing
  { name: 'Classic White T-Shirt', description: 'Premium cotton t-shirt, comfortable fit, machine washable', price: 24.99, originalPrice: 34.99, category: 'Fashion', subcategory: 'Clothing', brand: 'BasicWear', image: 'https://via.placeholder.com/300x300?text=White+T-Shirt', stock: 250, rating: 4.3, reviews: 1234, tags: ['tshirt', 'casual', 'cotton'], purchaseOptions: ['standard', 'bulk'], popularity: 75 },
  { name: 'Denim Jacket', description: 'Classic denim jacket with button closure, timeless style', price: 79.99, originalPrice: 99.99, category: 'Fashion', subcategory: 'Clothing', brand: 'Levi\'s', image: 'https://via.placeholder.com/300x300?text=Denim+Jacket', stock: 145, rating: 4.5, reviews: 876, tags: ['jacket', 'denim', 'casual'], purchaseOptions: ['standard'], popularity: 82 },
  { name: 'Chino Pants', description: 'Comfortable chino pants perfect for business casual', price: 59.99, originalPrice: 79.99, category: 'Fashion', subcategory: 'Clothing', brand: 'Gap', image: 'https://via.placeholder.com/300x300?text=Chino+Pants', stock: 178, rating: 4.4, reviews: 654, tags: ['pants', 'chino', 'business'], purchaseOptions: ['standard'], popularity: 78 },
  { name: 'Hooded Sweatshirt', description: 'Warm fleece sweatshirt with front pocket and drawstring hood', price: 49.99, originalPrice: 69.99, category: 'Fashion', subcategory: 'Clothing', brand: 'Champion', image: 'https://via.placeholder.com/300x300?text=Sweatshirt', stock: 198, rating: 4.6, reviews: 2345, tags: ['sweatshirt', 'hoodie', 'casual'], purchaseOptions: ['standard'], popularity: 84 },
  { name: 'Oxford Shirt', description: 'Classic button-down oxford shirt, perfect for office or casual wear', price: 44.99, originalPrice: 64.99, category: 'Fashion', subcategory: 'Clothing', brand: 'Banana Republic', image: 'https://via.placeholder.com/300x300?text=Oxford+Shirt', stock: 162, rating: 4.5, reviews: 987, tags: ['shirt', 'dress', 'formal'], purchaseOptions: ['standard'], popularity: 80 },
  { name: 'Leather Jacket', description: 'Genuine leather jacket with quilted lining, timeless style', price: 299.99, originalPrice: 399.99, category: 'Fashion', subcategory: 'Clothing', brand: 'Wilson\'s', image: 'https://via.placeholder.com/300x300?text=Leather+Jacket', stock: 56, rating: 4.7, reviews: 432, tags: ['jacket', 'leather', 'premium'], purchaseOptions: ['standard', 'express'], popularity: 86 },
  { name: 'Wool Coat', description: 'Warm winter coat made from premium wool blend', price: 199.99, originalPrice: 249.99, category: 'Fashion', subcategory: 'Clothing', brand: 'Calvin Klein', image: 'https://via.placeholder.com/300x300?text=Wool+Coat', stock: 73, rating: 4.6, reviews: 567, tags: ['coat', 'winter', 'wool'], purchaseOptions: ['standard', 'express'], popularity: 83 },
  { name: 'Athletic Shorts', description: 'Moisture-wicking athletic shorts with built-in liner', price: 34.99, originalPrice: 49.99, category: 'Fashion', subcategory: 'Clothing', brand: 'Nike', image: 'https://via.placeholder.com/300x300?text=Athletic+Shorts', stock: 234, rating: 4.5, reviews: 2345, tags: ['shorts', 'athletic', 'sports'], purchaseOptions: ['standard'], popularity: 81 },
  
  // Fashion - Shoes
  { name: 'Running Shoes', description: 'Lightweight running shoes with cushioning and breathable mesh', price: 119.99, originalPrice: 149.99, category: 'Fashion', subcategory: 'Shoes', brand: 'Nike', image: 'https://via.placeholder.com/300x300?text=Running+Shoes', stock: 189, rating: 4.6, reviews: 4567, tags: ['shoes', 'running', 'athletic'], purchaseOptions: ['standard', 'express'], popularity: 89 },
  { name: 'Casual Sneakers', description: 'Classic canvas sneakers perfect for everyday wear', price: 79.99, originalPrice: 99.99, category: 'Fashion', subcategory: 'Shoes', brand: 'Converse', image: 'https://via.placeholder.com/300x300?text=Sneakers', stock: 267, rating: 4.4, reviews: 6789, tags: ['shoes', 'sneakers', 'casual'], purchaseOptions: ['standard'], popularity: 87 },
  { name: 'Dress Shoes', description: 'Premium leather dress shoes for formal occasions', price: 149.99, originalPrice: 199.99, category: 'Fashion', subcategory: 'Shoes', brand: 'Cole Haan', image: 'https://via.placeholder.com/300x300?text=Dress+Shoes', stock: 98, rating: 4.7, reviews: 1234, tags: ['shoes', 'dress', 'formal'], purchaseOptions: ['standard', 'express'], popularity: 84 },
  { name: 'Hiking Boots', description: 'Waterproof hiking boots with ankle support and rugged sole', price: 179.99, originalPrice: 229.99, category: 'Fashion', subcategory: 'Shoes', brand: 'Merrell', image: 'https://via.placeholder.com/300x300?text=Hiking+Boots', stock: 124, rating: 4.6, reviews: 987, tags: ['shoes', 'hiking', 'outdoor'], purchaseOptions: ['standard', 'express'], popularity: 82 },
  { name: 'Basketball Shoes', description: 'High-top basketball shoes with responsive cushioning', price: 129.99, originalPrice: 159.99, category: 'Fashion', subcategory: 'Shoes', brand: 'Adidas', image: 'https://via.placeholder.com/300x300?text=Basketball+Shoes', stock: 156, rating: 4.5, reviews: 2345, tags: ['shoes', 'basketball', 'sports'], purchaseOptions: ['standard', 'express'], popularity: 85 },
  
  // Home & Kitchen
  { name: 'Stainless Steel Cookware Set', description: '10-piece non-stick cookware set for all your cooking needs', price: 199.99, originalPrice: 279.99, category: 'Home & Kitchen', subcategory: 'Cookware', brand: 'Cuisinart', image: 'https://via.placeholder.com/300x300?text=Cookware+Set', stock: 78, rating: 4.6, reviews: 3456, tags: ['cookware', 'kitchen', 'stainless'], purchaseOptions: ['standard', 'express'], popularity: 86 },
  { name: 'Stand Mixer', description: 'Professional stand mixer with 5.5QT bowl and multiple attachments', price: 399.99, originalPrice: 499.99, category: 'Home & Kitchen', subcategory: 'Appliances', brand: 'KitchenAid', image: 'https://via.placeholder.com/300x300?text=Stand+Mixer', stock: 45, rating: 4.8, reviews: 5678, tags: ['mixer', 'kitchen', 'appliance'], purchaseOptions: ['standard', 'express'], popularity: 90 },
  { name: 'Air Fryer', description: '6QT air fryer with digital display and multiple cooking functions', price: 129.99, originalPrice: 179.99, category: 'Home & Kitchen', subcategory: 'Appliances', brand: 'Ninja', image: 'https://via.placeholder.com/300x300?text=Air+Fryer', stock: 112, rating: 4.7, reviews: 8901, tags: ['air fryer', 'kitchen', 'healthy'], purchaseOptions: ['standard', 'express'], popularity: 94 },
  { name: 'Coffee Maker', description: 'Programmable drip coffee maker with thermal carafe', price: 89.99, originalPrice: 119.99, category: 'Home & Kitchen', subcategory: 'Appliances', brand: 'Cuisinart', image: 'https://via.placeholder.com/300x300?text=Coffee+Maker', stock: 134, rating: 4.5, reviews: 4567, tags: ['coffee', 'maker', 'kitchen'], purchaseOptions: ['standard'], popularity: 88 },
  { name: 'Bedding Set', description: 'Queen size sheet set with comforter, pillowcases, and shams', price: 79.99, originalPrice: 119.99, category: 'Home & Kitchen', subcategory: 'Bedding', brand: 'Bamboo', image: 'https://via.placeholder.com/300x300?text=Bedding+Set', stock: 167, rating: 4.4, reviews: 2345, tags: ['bedding', 'sheets', 'home'], purchaseOptions: ['standard'], popularity: 81 },
  { name: 'Kitchen Knife Set', description: 'Professional 8-piece knife set with block and sharpener', price: 149.99, originalPrice: 199.99, category: 'Home & Kitchen', subcategory: 'Cutlery', brand: 'Henckels', image: 'https://via.placeholder.com/300x300?text=Knife+Set', stock: 92, rating: 4.7, reviews: 3456, tags: ['knives', 'kitchen', 'cutlery'], purchaseOptions: ['standard', 'express'], popularity: 87 },
  { name: 'Rice Cooker', description: 'Fuzzy logic rice cooker with multiple cooking modes', price: 69.99, originalPrice: 99.99, category: 'Home & Kitchen', subcategory: 'Appliances', brand: 'Zojirushi', image: 'https://via.placeholder.com/300x300?text=Rice+Cooker', stock: 145, rating: 4.6, reviews: 5678, tags: ['rice cooker', 'kitchen', 'appliance'], purchaseOptions: ['standard'], popularity: 84 },
  { name: 'Vacuum Cleaner', description: 'Bagless upright vacuum with HEPA filter and multiple attachments', price: 199.99, originalPrice: 279.99, category: 'Home & Kitchen', subcategory: 'Appliances', brand: 'Shark', image: 'https://via.placeholder.com/300x300?text=Vacuum', stock: 83, rating: 4.5, reviews: 4321, tags: ['vacuum', 'cleaning', 'home'], purchaseOptions: ['standard', 'express'], popularity: 82 },
  
  // Sports & Outdoors
  { name: 'Yoga Mat', description: 'Extra-thick non-slip yoga mat with carrying strap', price: 34.99, originalPrice: 49.99, category: 'Sports & Outdoors', subcategory: 'Fitness', brand: 'Liforme', image: 'https://via.placeholder.com/300x300?text=Yoga+Mat', stock: 234, rating: 4.5, reviews: 6789, tags: ['yoga', 'mat', 'fitness'], purchaseOptions: ['standard'], popularity: 83 },
  { name: 'Dumbbell Set', description: 'Adjustable dumbbell set 5-50lbs per dumbbell', price: 299.99, originalPrice: 399.99, category: 'Sports & Outdoors', subcategory: 'Fitness', brand: 'Bowflex', image: 'https://via.placeholder.com/300x300?text=Dumbbells', stock: 56, rating: 4.6, reviews: 2345, tags: ['weights', 'fitness', 'gym'], purchaseOptions: ['standard', 'express'], popularity: 85 },
  { name: 'Camping Tent 4-Person', description: 'Weather-resistant camping tent with rainfly and carrying bag', price: 149.99, originalPrice: 199.99, category: 'Sports & Outdoors', subcategory: 'Camping', brand: 'Coleman', image: 'https://via.placeholder.com/300x300?text=Camping+Tent', stock: 98, rating: 4.6, reviews: 4321, tags: ['tent', 'camping', 'outdoor'], purchaseOptions: ['standard', 'express'], popularity: 86 },
  { name: 'Cooler 50QT', description: 'Hard-sided cooler with superior ice retention', price: 199.99, originalPrice: 249.99, category: 'Sports & Outdoors', subcategory: 'Camping', brand: 'Yeti', image: 'https://via.placeholder.com/300x300?text=Cooler', stock: 67, rating: 4.7, reviews: 5678, tags: ['cooler', 'camping', 'outdoor'], purchaseOptions: ['standard', 'express'], popularity: 87 },
  { name: 'Backpack 40L', description: 'Hiking backpack with hydration system and multiple compartments', price: 129.99, originalPrice: 179.99, category: 'Sports & Outdoors', subcategory: 'Outdoor Gear', brand: 'Osprey', image: 'https://via.placeholder.com/300x300?text=Backpack', stock: 145, rating: 4.8, reviews: 3456, tags: ['backpack', 'hiking', 'outdoor'], purchaseOptions: ['standard', 'express'], popularity: 88 },
  { name: 'Bicycle Helmet', description: 'Lightweight bike helmet with MIPS protection', price: 79.99, originalPrice: 119.99, category: 'Sports & Outdoors', subcategory: 'Cycling', brand: 'Giro', image: 'https://via.placeholder.com/300x300?text=Bike+Helmet', stock: 178, rating: 4.5, reviews: 5678, tags: ['helmet', 'bike', 'safety'], purchaseOptions: ['standard'], popularity: 84 },
  { name: 'Resistance Bands Set', description: 'Set of 5 resistance bands with door anchor and handles', price: 24.99, originalPrice: 39.99, category: 'Sports & Outdoors', subcategory: 'Fitness', brand: 'Bodylastics', image: 'https://via.placeholder.com/300x300?text=Resistance+Bands', stock: 267, rating: 4.4, reviews: 4321, tags: ['fitness', 'bands', 'exercise'], purchaseOptions: ['standard'], popularity: 79 },
  { name: 'Golf Club Set', description: 'Complete golf club set with bag, driver, irons, and putter', price: 499.99, originalPrice: 699.99, category: 'Sports & Outdoors', subcategory: 'Golf', brand: 'Callaway', image: 'https://via.placeholder.com/300x300?text=Golf+Clubs', stock: 34, rating: 4.7, reviews: 876, tags: ['golf', 'clubs', 'sports'], purchaseOptions: ['standard', 'express', 'warranty'], popularity: 83 },
  
  // Books & Media
  { name: 'Kindle Paperwhite', description: 'Waterproof e-reader with 6.8" display and adjustable light', price: 139.99, originalPrice: 169.99, category: 'Books & Media', subcategory: 'E-Readers', brand: 'Amazon', image: 'https://via.placeholder.com/300x300?text=Kindle', stock: 156, rating: 4.7, reviews: 8901, tags: ['kindle', 'ebook', 'reading'], purchaseOptions: ['standard', 'express'], popularity: 91 },
  { name: 'Wireless Earbuds', description: 'Budget-friendly wireless earbuds with 24-hour battery', price: 39.99, originalPrice: 59.99, category: 'Books & Media', subcategory: 'Audio', brand: 'Anker', image: 'https://via.placeholder.com/300x300?text=Earbuds', stock: 289, rating: 4.3, reviews: 12345, tags: ['earbuds', 'wireless', 'budget'], purchaseOptions: ['standard'], popularity: 88 },
  
  // Beauty & Personal Care
  { name: 'Electric Toothbrush', description: 'Sonic toothbrush with 5 cleaning modes and timer', price: 99.99, originalPrice: 149.99, category: 'Beauty & Personal Care', subcategory: 'Oral Care', brand: 'Oral-B', image: 'https://via.placeholder.com/300x300?text=Toothbrush', stock: 234, rating: 4.6, reviews: 6789, tags: ['toothbrush', 'electric', 'oral'], purchaseOptions: ['standard'], popularity: 85 },
  { name: 'Hair Dryer Professional', description: 'Ionic hair dryer with multiple heat settings and diffuser', price: 129.99, originalPrice: 179.99, category: 'Beauty & Personal Care', subcategory: 'Hair Care', brand: 'Revlon', image: 'https://via.placeholder.com/300x300?text=Hair+Dryer', stock: 167, rating: 4.5, reviews: 4567, tags: ['hair dryer', 'beauty', 'styling'], purchaseOptions: ['standard'], popularity: 82 },
  { name: 'Skincare Set', description: 'Complete skincare routine with cleanser, toner, and moisturizer', price: 79.99, originalPrice: 119.99, category: 'Beauty & Personal Care', subcategory: 'Skincare', brand: 'Cetaphil', image: 'https://via.placeholder.com/300x300?text=Skincare', stock: 198, rating: 4.4, reviews: 3456, tags: ['skincare', 'beauty', 'routine'], purchaseOptions: ['standard'], popularity: 80 },
  
  // Toys & Games
  { name: 'LEGO Creator Set', description: '3-in-1 building set with 1000+ pieces', price: 79.99, originalPrice: 99.99, category: 'Toys & Games', subcategory: 'Building Toys', brand: 'LEGO', image: 'https://via.placeholder.com/300x300?text=LEGO', stock: 234, rating: 4.8, reviews: 8901, tags: ['lego', 'building', 'toys'], purchaseOptions: ['standard', 'express'], popularity: 92 },
  { name: 'Board Game Collection', description: 'Set of 5 popular board games for family fun', price: 89.99, originalPrice: 129.99, category: 'Toys & Games', subcategory: 'Board Games', brand: 'Hasbro', image: 'https://via.placeholder.com/300x300?text=Board+Games', stock: 145, rating: 4.6, reviews: 2345, tags: ['board games', 'toys', 'family'], purchaseOptions: ['standard'], popularity: 84 },
  { name: 'Remote Control Drone', description: 'HD camera drone with altitude hold and headless mode', price: 149.99, originalPrice: 199.99, category: 'Toys & Games', subcategory: 'Remote Control', brand: 'DJI', image: 'https://via.placeholder.com/300x300?text=Drone', stock: 78, rating: 4.7, reviews: 5678, tags: ['drone', 'rc', 'camera'], purchaseOptions: ['standard', 'express'], popularity: 87 },
  
  // Automotive
  { name: 'Car Phone Mount', description: 'Magnetic car mount with one-handed operation', price: 19.99, originalPrice: 29.99, category: 'Automotive', subcategory: 'Accessories', brand: 'iOttie', image: 'https://via.placeholder.com/300x300?text=Phone+Mount', stock: 456, rating: 4.5, reviews: 12345, tags: ['car', 'mount', 'phone'], purchaseOptions: ['standard'], popularity: 86 },
  { name: 'Car Charger', description: 'Dual USB car charger with fast charging technology', price: 14.99, originalPrice: 24.99, category: 'Automotive', subcategory: 'Accessories', brand: 'Anker', image: 'https://via.placeholder.com/300x300?text=Car+Charger', stock: 567, rating: 4.4, reviews: 8901, tags: ['car', 'charger', 'usb'], purchaseOptions: ['standard'], popularity: 83 },
  
  // Pet Supplies
  { name: 'Automatic Pet Feeder', description: 'Programmable pet feeder with portion control', price: 89.99, originalPrice: 129.99, category: 'Pet Supplies', subcategory: 'Feeders', brand: 'PetSafe', image: 'https://via.placeholder.com/300x300?text=Pet+Feeder', stock: 123, rating: 4.6, reviews: 4321, tags: ['pet', 'feeder', 'automatic'], purchaseOptions: ['standard'], popularity: 84 },
  { name: 'Dog Bed Orthopedic', description: 'Memory foam dog bed for large dogs', price: 79.99, originalPrice: 119.99, category: 'Pet Supplies', subcategory: 'Beds', brand: 'Furhaven', image: 'https://via.placeholder.com/300x300?text=Dog+Bed', stock: 189, rating: 4.5, reviews: 5678, tags: ['dog', 'bed', 'pet'], purchaseOptions: ['standard'], popularity: 81 },
  
  // Health & Wellness
  { name: 'Air Purifier', description: 'HEPA air purifier for rooms up to 500 sq ft', price: 199.99, originalPrice: 279.99, category: 'Health & Wellness', subcategory: 'Air Quality', brand: 'Honeywell', image: 'https://via.placeholder.com/300x300?text=Air+Purifier', stock: 98, rating: 4.6, reviews: 3456, tags: ['air purifier', 'health', 'hepa'], purchaseOptions: ['standard', 'express'], popularity: 85 },
  { name: 'Blood Pressure Monitor', description: 'Digital upper arm blood pressure monitor', price: 49.99, originalPrice: 79.99, category: 'Health & Wellness', subcategory: 'Medical', brand: 'Omron', image: 'https://via.placeholder.com/300x300?text=BP+Monitor', stock: 167, rating: 4.5, reviews: 4321, tags: ['health', 'monitor', 'medical'], purchaseOptions: ['standard'], popularity: 82 },
  
  // Office Supplies
  { name: 'Ergonomic Office Chair', description: 'Mesh office chair with lumbar support and adjustable height', price: 299.99, originalPrice: 399.99, category: 'Office Supplies', subcategory: 'Furniture', brand: 'Herman Miller', image: 'https://via.placeholder.com/300x300?text=Office+Chair', stock: 56, rating: 4.7, reviews: 2345, tags: ['chair', 'office', 'ergonomic'], purchaseOptions: ['standard', 'express'], popularity: 89 },
  { name: 'Standing Desk Converter', description: 'Adjustable standing desk converter for any desk', price: 199.99, originalPrice: 279.99, category: 'Office Supplies', subcategory: 'Furniture', brand: 'FlexiSpot', image: 'https://via.placeholder.com/300x300?text=Standing+Desk', stock: 78, rating: 4.6, reviews: 3456, tags: ['desk', 'standing', 'office'], purchaseOptions: ['standard', 'express'], popularity: 86 },
  
  // More Electronics Accessories
  { name: 'USB-C Hub 8-in-1', description: 'Multi-port hub with HDMI, USB 3.0, SD card reader', price: 49.99, originalPrice: 69.99, category: 'Electronics', subcategory: 'Accessories', brand: 'Anker', image: 'https://via.placeholder.com/300x300?text=USB+Hub', stock: 234, rating: 4.5, reviews: 6789, tags: ['usb hub', 'accessories', 'usb-c'], purchaseOptions: ['standard'], popularity: 84 },
  { name: 'Laptop Stand Aluminum', description: 'Adjustable aluminum laptop stand for better ergonomics', price: 39.99, originalPrice: 59.99, category: 'Electronics', subcategory: 'Accessories', brand: 'Rain Design', image: 'https://via.placeholder.com/300x300?text=Laptop+Stand', stock: 178, rating: 4.4, reviews: 4321, tags: ['laptop stand', 'accessories', 'ergonomic'], purchaseOptions: ['standard'], popularity: 81 },
  { name: 'Webcam 4K', description: '4K webcam with auto-focus and built-in microphone', price: 129.99, originalPrice: 179.99, category: 'Electronics', subcategory: 'Accessories', brand: 'Logitech', image: 'https://via.placeholder.com/300x300?text=Webcam', stock: 145, rating: 4.6, reviews: 5678, tags: ['webcam', 'video', 'accessories'], purchaseOptions: ['standard', 'express'], popularity: 85 },
  { name: 'External Hard Drive 2TB', description: 'Portable 2TB USB 3.0 external hard drive', price: 79.99, originalPrice: 119.99, category: 'Electronics', subcategory: 'Storage', brand: 'Seagate', image: 'https://via.placeholder.com/300x300?text=Hard+Drive', stock: 198, rating: 4.5, reviews: 8901, tags: ['hard drive', 'storage', 'usb'], purchaseOptions: ['standard'], popularity: 83 },
  { name: 'SSD 1TB External', description: 'Fast external SSD with USB-C connection, 1050MB/s', price: 149.99, originalPrice: 199.99, category: 'Electronics', subcategory: 'Storage', brand: 'Samsung', image: 'https://via.placeholder.com/300x300?text=SSD', stock: 167, rating: 4.7, reviews: 3456, tags: ['ssd', 'storage', 'fast'], purchaseOptions: ['standard', 'express'], popularity: 87 },
  
  // Additional Products to reach 100
  { name: 'iPhone 14', description: 'Previous generation iPhone with A15 Bionic chip and excellent cameras', price: 699.99, originalPrice: 799.99, category: 'Electronics', subcategory: 'Smartphones', brand: 'Apple', image: 'https://via.placeholder.com/300x300?text=iPhone+14', stock: 92, rating: 4.7, reviews: 3456, tags: ['smartphone', 'apple', 'iphone'], purchaseOptions: ['standard', 'express'], popularity: 86 },
  { name: 'Samsung Galaxy Buds2 Pro', description: 'Premium true wireless earbuds with active noise cancellation', price: 199.99, originalPrice: 249.99, category: 'Electronics', subcategory: 'Audio', brand: 'Samsung', image: 'https://via.placeholder.com/300x300?text=Galaxy+Buds', stock: 156, rating: 4.6, reviews: 2345, tags: ['earbuds', 'wireless', 'samsung'], purchaseOptions: ['standard', 'express'], popularity: 84 },
  { name: 'iPad Air 5th Gen', description: '10.9-inch tablet with M1 chip and all-day battery life', price: 599.99, originalPrice: 649.99, category: 'Electronics', subcategory: 'Tablets', brand: 'Apple', image: 'https://via.placeholder.com/300x300?text=iPad+Air', stock: 78, rating: 4.8, reviews: 5678, tags: ['tablet', 'apple', 'ipad'], purchaseOptions: ['standard', 'express', 'warranty'], popularity: 91 },
  { name: 'Surface Pro 9', description: '2-in-1 tablet with detachable keyboard and Windows 11', price: 999.99, originalPrice: 1149.99, category: 'Electronics', subcategory: 'Tablets', brand: 'Microsoft', image: 'https://via.placeholder.com/300x300?text=Surface+Pro', stock: 45, rating: 4.6, reviews: 1234, tags: ['tablet', 'microsoft', 'windows'], purchaseOptions: ['standard', 'express', 'premium'], popularity: 87 },
  { name: 'Nikon D850 DSLR', description: 'Professional full-frame DSLR camera with 45.7MP sensor', price: 2999.99, originalPrice: 3299.99, category: 'Electronics', subcategory: 'Cameras', brand: 'Nikon', image: 'https://via.placeholder.com/300x300?text=Nikon+D850', stock: 23, rating: 4.9, reviews: 567, tags: ['camera', 'dslr', 'nikon'], purchaseOptions: ['standard', 'express', 'premium', 'warranty'], popularity: 89 },
  { name: 'Sony WH-1000XM4', description: 'Previous gen noise-cancelling headphones with exceptional audio', price: 279.99, originalPrice: 349.99, category: 'Electronics', subcategory: 'Audio', brand: 'Sony', image: 'https://via.placeholder.com/300x300?text=Sony+XM4', stock: 98, rating: 4.7, reviews: 8901, tags: ['headphones', 'wireless', 'sony'], purchaseOptions: ['standard', 'express'], popularity: 90 },
  { name: 'Gaming Chair Pro', description: 'Ergonomic gaming chair with lumbar support and RGB lighting', price: 399.99, originalPrice: 499.99, category: 'Electronics', subcategory: 'Gaming', brand: 'Secretlab', image: 'https://via.placeholder.com/300x300?text=Gaming+Chair', stock: 67, rating: 4.8, reviews: 4567, tags: ['chair', 'gaming', 'ergonomic'], purchaseOptions: ['standard', 'express'], popularity: 88 },
  { name: 'DJI Mini 3 Drone', description: 'Compact drone with 4K camera and 38-minute flight time', price: 599.99, originalPrice: 749.99, category: 'Electronics', subcategory: 'Cameras', brand: 'DJI', image: 'https://via.placeholder.com/300x300?text=DJI+Mini+3', stock: 54, rating: 4.7, reviews: 2345, tags: ['drone', 'camera', 'dji'], purchaseOptions: ['standard', 'express'], popularity: 86 },
  { name: 'Sneakers Running Pro', description: 'Advanced running shoes with cushioning and breathable upper', price: 149.99, originalPrice: 179.99, category: 'Fashion', subcategory: 'Shoes', brand: 'Adidas', image: 'https://via.placeholder.com/300x300?text=Running+Shoes', stock: 289, rating: 4.6, reviews: 6789, tags: ['shoes', 'running', 'adidas'], purchaseOptions: ['standard', 'express'], popularity: 87 },
  { name: 'Leather Wallet', description: 'Genuine leather wallet with RFID blocking and card slots', price: 49.99, originalPrice: 69.99, category: 'Fashion', subcategory: 'Accessories', brand: 'Fossil', image: 'https://via.placeholder.com/300x300?text=Wallet', stock: 234, rating: 4.5, reviews: 4321, tags: ['wallet', 'leather', 'accessories'], purchaseOptions: ['standard'], popularity: 82 },
  { name: 'Smart Light Bulbs 4-Pack', description: 'WiFi-enabled color changing LED bulbs with app control', price: 79.99, originalPrice: 99.99, category: 'Electronics', subcategory: 'Smart Home', brand: 'Philips Hue', image: 'https://via.placeholder.com/300x300?text=Smart+Bulbs', stock: 178, rating: 4.6, reviews: 5678, tags: ['smart lights', 'home', 'wifi'], purchaseOptions: ['standard', 'bulk'], popularity: 85 },
  { name: 'Kitchen Scale Digital', description: 'Precision digital kitchen scale with 11lb capacity', price: 24.99, originalPrice: 34.99, category: 'Home & Kitchen', subcategory: 'Appliances', brand: 'OXO', image: 'https://via.placeholder.com/300x300?text=Kitchen+Scale', stock: 267, rating: 4.5, reviews: 8901, tags: ['scale', 'kitchen', 'digital'], purchaseOptions: ['standard'], popularity: 81 },
  { name: 'Wireless Mouse Ergonomic', description: 'Ergonomic wireless mouse with precision tracking and long battery', price: 69.99, originalPrice: 89.99, category: 'Electronics', subcategory: 'Accessories', brand: 'Logitech', image: 'https://via.placeholder.com/300x300?text=Ergonomic+Mouse', stock: 198, rating: 4.6, reviews: 3456, tags: ['mouse', 'wireless', 'ergonomic'], purchaseOptions: ['standard', 'express'], popularity: 84 },
  { name: 'Blender Professional', description: 'High-speed blender with 64oz pitcher and multiple speeds', price: 149.99, originalPrice: 199.99, category: 'Home & Kitchen', subcategory: 'Appliances', brand: 'Vitamix', image: 'https://via.placeholder.com/300x300?text=Blender', stock: 87, rating: 4.8, reviews: 6789, tags: ['blender', 'kitchen', 'appliance'], purchaseOptions: ['standard', 'express'], popularity: 89 },
  { name: 'Table Tennis Set', description: 'Complete table tennis set with paddles, balls, and net', price: 129.99, originalPrice: 179.99, category: 'Sports & Outdoors', subcategory: 'Indoor Sports', brand: 'Stiga', image: 'https://via.placeholder.com/300x300?text=Ping+Pong', stock: 123, rating: 4.5, reviews: 2345, tags: ['table tennis', 'sports', 'indoor'], purchaseOptions: ['standard', 'express'], popularity: 80 },
  { name: 'Instant Pot Duo', description: '7-in-1 electric pressure cooker with multiple cooking functions', price: 99.99, originalPrice: 149.99, category: 'Home & Kitchen', subcategory: 'Appliances', brand: 'Instant Pot', image: 'https://via.placeholder.com/300x300?text=Instant+Pot', stock: 145, rating: 4.7, reviews: 12345, tags: ['pressure cooker', 'kitchen', 'electric'], purchaseOptions: ['standard', 'express'], popularity: 92 },
];

const coupons = [
  { code: 'WELCOME10', discount: 10, type: 'percentage', minPurchase: 50, maxDiscount: 100, validFrom: new Date('2024-01-01'), validTo: new Date('2024-12-31'), usageLimit: 1000, usedCount: 245, active: true },
  { code: 'SAVE20', discount: 20, type: 'percentage', minPurchase: 100, maxDiscount: 200, validFrom: new Date('2024-01-01'), validTo: new Date('2024-12-31'), usageLimit: 500, usedCount: 189, active: true },
  { code: 'FLAT50', discount: 50, type: 'fixed', minPurchase: 200, maxDiscount: 50, validFrom: new Date('2024-01-01'), validTo: new Date('2024-12-31'), usageLimit: 200, usedCount: 45, active: true },
  { code: 'SUMMER25', discount: 25, type: 'percentage', minPurchase: 75, maxDiscount: 150, validFrom: new Date('2024-06-01'), validTo: new Date('2024-08-31'), usageLimit: 300, usedCount: 98, active: true },
];

async function seedDatabase() {
  try {
    await connectDB();
    
    // Clear existing data
    await Product.deleteMany({});
    await Coupon.deleteMany({});
    
    console.log('Seeding products...');
    await Product.insertMany(products);
    console.log(`✓ Inserted ${products.length} products`);
    
    console.log('Seeding coupons...');
    await Coupon.insertMany(coupons);
    console.log(`✓ Inserted ${coupons.length} coupons`);
    
    console.log('Database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seedDatabase();

